spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  data:
    redis:
      port: 6379
      host: localhost
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
open:
  api:
    title: API Document
    version: v1.0.0
    description: E-Learning System API Service
    serverUrl: http://localhost:8080
    serverName: Local Dev Server

jwt:
  secret-key: ${JWT_SECRET_KEY}
  valid-duration: 300
  refreshable-duration: 1800
outbound:
  identity:
    client-id: ${OUTBOUND_IDENTITY_CLIENT_ID}
    client-secret: ${OUTBOUND_IDENTITY_CLIENT_SECRET}
    redirect-uri: ${OUTBOUND_IDENTITY_REDIRECT_URI}
  facebook:
    client-id: ${OUTBOUND_FACEBOOK_CLIENT_ID:}
    client-secret: ${OUTBOUND_FACEBOOK_CLIENT_SECRET:}
    redirect-uri: ${OUTBOUND_FACEBOOK_REDIRECT_URI:}
management:
  endpoint:
    web:
      exposure:
        include: "*"
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

payment:
  vnPay:
    url: ${VNPAY_URL}
    tmn-code: ${VNPAY_TMN_CODE}
    secret-key: ${VNPAY_SECRET_KEY}
    return-url: ${VNPAY_RETURN_URL}
    version: 2.1.0
    command: pay
    order-type: other

# File upload configuration
file:
  upload:
    dir: uploads/videos

