spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

open:
  api:
    title: API Document
    version: v1.0.0
    description: Cinema API service
    serverUrl: http://localhost:8080
    serverName: Local Dev Server
